// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjDoumqsrP8ZZL42AdTDdMhGDlrGpX-3E',
    appId: '1:1069896559925:web:c8238a68ae92b9c4a4f07c',
    messagingSenderId: '1069896559925',
    projectId: 'test-f9c06',
    authDomain: 'test-f9c06.firebaseapp.com',
    storageBucket: 'test-f9c06.appspot.com',
    measurementId: 'G-MLJ0Q0DLEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj75-2V56ZprSXQeHOv3GQOqLGZ9bT5BE',
    appId: '1:1069896559925:android:c6c496df0239b5fca4f07c',
    messagingSenderId: '1069896559925',
    projectId: 'test-f9c06',
    storageBucket: 'test-f9c06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa8mbdrU0ugmKkfYoRFCo1XYMLFBxwGvg',
    appId: '1:1069896559925:ios:192ca888be2cf1e7a4f07c',
    messagingSenderId: '1069896559925',
    projectId: 'test-f9c06',
    storageBucket: 'test-f9c06.appspot.com',
    iosClientId: '1069896559925-06g3i100rsakpllh0eo7vo4i3bs787dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa8mbdrU0ugmKkfYoRFCo1XYMLFBxwGvg',
    appId: '1:1069896559925:ios:e63f6a678f44b42ea4f07c',
    messagingSenderId: '1069896559925',
    projectId: 'test-f9c06',
    storageBucket: 'test-f9c06.appspot.com',
    iosClientId: '1069896559925-00el80q7ur8ggqc3lrq685mugdvl8kf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
